# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"9\n\rWalletRequest\x12\x0c\n\x04\x63\x61ll\x18\x01 \x01(\t\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_data\" \n\x0eWalletResponse\x12\x0e\n\x06result\x18\x01 \x01(\t29\n\x0cWalletServer\x12)\n\x04\x43\x61ll\x12\x0e.WalletRequest\x1a\x0f.WalletResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_WALLETREQUEST']._serialized_start=16
  _globals['_WALLETREQUEST']._serialized_end=73
  _globals['_WALLETRESPONSE']._serialized_start=75
  _globals['_WALLETRESPONSE']._serialized_end=107
  _globals['_WALLETSERVER']._serialized_start=109
  _globals['_WALLETSERVER']._serialized_end=166
# @@protoc_insertion_point(module_scope)
